# Generated by Django 3.0 on 2020-04-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Australia', 'Australia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America')], max_length=15, unique=True, verbose_name='Continent')),
                ('avgAge', models.FloatField(verbose_name='Average Age')),
                ('avgDailyIncomeInUsd', models.FloatField(default=1.5, verbose_name='Average Income In USD')),
                ('avgDailyIncomePopulation', models.FloatField(default=0.65, verbose_name='Average Daily Income Population')),
                ('period', models.FloatField(verbose_name='days')),
                ('timeToElapse', models.FloatField(blank=True, null=True, verbose_name='Time To Elapse')),
                ('reportedCases', models.FloatField(verbose_name='reported_cases')),
                ('population', models.FloatField(verbose_name='Population')),
                ('totalHospitalBeds', models.FloatField(verbose_name='Total Hospital Beds')),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('currentlyInfected', models.FloatField(verbose_name='Currently Infected')),
                ('InfectionByRequestedTime', models.FloatField(verbose_name='Infections By Requested Time')),
                ('severeCasesByRequestedTime_impact', models.FloatField(verbose_name='Severe Cases By Requested Time')),
                ('hospitalBedsByRequestedTime_impact', models.FloatField(verbose_name='Hospital Beds')),
                ('casesForICUByRequestedTime_impact', models.FloatField(verbose_name='Cases For ICU')),
                ('casesForVentilatorsByRequestedTime_impact', models.FloatField(verbose_name='Cases For Ventilators')),
                ('dollarsInFlight_impact', models.FloatField(verbose_name='Dollars In Flight')),
            ],
        ),
        migrations.CreateModel(
            name='SevereImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Continent')),
                ('currentlyInfectedsevere', models.FloatField(verbose_name='Currently Infected')),
                ('InfectionByRequestedTimeSevere', models.FloatField(verbose_name='Infections By Requested Time')),
                ('severeCasesByRequestedTime_severe', models.FloatField(verbose_name='Severe Cases By Requested Time')),
                ('hospitalBedsByRequestedTime_severe', models.FloatField(verbose_name='Hospital Beds')),
                ('casesForICUByRequestedTime_severe', models.FloatField(verbose_name='Cases For ICU')),
                ('casesForVentilatorsByRequestedTime_severe', models.FloatField(verbose_name='Cases For Ventilators')),
                ('dollarsInFlight_severe', models.FloatField(verbose_name='Dollars In Flight')),
            ],
        ),
    ]
