# Generated by Django 3.0 on 2020-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Australia', 'Australia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America')], max_length=15)),
                ('avgAge', models.IntegerField()),
                ('avgDailyIncomeInUsd', models.IntegerField(default=1.5)),
                ('avgDailyIncomePopulation', models.IntegerField(default=0.17)),
                ('period', models.IntegerField(verbose_name='days')),
                ('timeToElapse', models.IntegerField()),
                ('reportedCases', models.IntegerField(verbose_name='reported_cases')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('totalHospitalBeds', models.IntegerField(verbose_name='Total Hospital Beds')),
            ],
        ),
    ]
