# Generated by Django 3.0 on 2020-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200416_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19',
            name='name',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Australia', 'Australia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America')], max_length=15, unique=True, verbose_name='Continent'),
        ),
    ]
